name: Build Shiny Docker Image and Deploy to Heroku

on:
  push:
    branches:
      - main
      - master

jobs:
  deploy:
    name: Build and deploy Shiny app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and push Docker to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          # this is the Heroku app name you already set up in dashboard
          heroku_app_name: shiny-example
          # app directory needs to be set relative to root of repo
          appdir: "."
          # secrets need to be added to the GitHub repo settings
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          # don't change this
          usedocker: true
